### ISSUE TITLE
Getting 500 error when making API request using the quickstart vagrant up for ozp-ansible

### ISSUE THREAD

**Issue by ncutt010** [ozone-development/ozp-ansible#1]
I've pulled the latest ozp-ansible project and am currently trying to quick start a vagrant build.  The build stands OZP without errors but when I try an hit any `/api` request I get a 500 error in the browser.  ie `https://localhost:4440/api/user/`.

The ozp.log throws the following error
```
hitting url http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None for user with dn Big Brother bigbrother
Internal Server Error: /api/user/
Traceback (most recent call last):
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 377, in initial
    self.check_permissions(request)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 318, in check_permissions
    if not permission.has_permission(request, self):
  File "/usr/local/ozp/backend/ozpcenter/permissions.py", line 67, in has_permission
    ozp_authorization.authorization_update(request.user.username)
  File "/usr/local/ozp/backend/ozpcenter/auth/ozp_authorization.py", line 127, in authorization_update
    updated_auth_data = _get_auth_data(username)
  File "/usr/local/ozp/backend/ozpcenter/auth/ozp_authorization.py", line 54, in _get_auth_data
    raise errors.AuthorizationFailure('Error contacting authorization server: %s' % r.text)
ozpcenter.errors.AuthorizationFailure: Error contacting authorization server: <HEAD><TITLE>Unknown Host</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Unknown Host</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: Unable to locate the server named "<em>localhost</em>" --- the server does not have a DNS entry.  Perhaps there is a misspelling in the server name, or the server no longer exists.  Double-check the name and try again.</B></FONT>
<HR>
<!-- default "Unknown Host" response (504) -->
</BODY>
```

It appears the issue might have to do with the gunicorn_demoauth service since it uses port 8081. In order to redeploy this service I had to manually kill the process because running `service gunicorn_demoauth stop` failed. However redeploying still didnt resolve my issue.

Here's gunicorn_demoauth log:
```
[2016-02-18 19:17:09 +0000] [5748] [INFO] Starting gunicorn 19.3.0
[2016-02-18 19:17:09 +0000] [5748] [INFO] Listening at: http://0.0.0.0:8081 (5748)
[2016-02-18 19:17:09 +0000] [5748] [INFO] Using worker: sync
[2016-02-18 19:17:09 +0000] [5751] [INFO] Booting worker with pid: 5751
[2016-02-18 19:17:09 +0000] [5752] [INFO] Booting worker with pid: 5752
```

Any thoughts/tips would be greatly appreciated!

Current setup:
Virtualbox v5.0.14
Vagrant v1.8.1

**Comment by clarkjefcoat** [comment]
That error message is a really strange one.

Maybe nginx started before the demo_auth server started?  Please try logging in to the vagrant box and restarting nginx:

```sudo service nginx restart```

If that doesn't fix your problem, what happens if you try to connect to the auth server while logged into the vagrant box?  Try the wget command below.  You should get a bunch of fake clearance test data back.

```
[vagrant@localhost ~]$ wget -qO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
{"clearances":["UNCLASSIFIED","CONFIDENTIAL","SECRET","TOP SECRET"],"dutyorg":"Minipax","dn":"Big Brother bigbrother","formalAccesses":["SIERRA","TANGO","GOLF","HOTEL"],"visas":["NOVEMBER"]}
[vagrant@localhost ~]$ 
```

Current setup:
My host machine is running Ubuntu 14.04.
Virtualbox v5.0.14
Vagrant v1.8.1

**Comment by ncutt010** [comment]
Thanks for the response, 

Unfortunately, restarting nginx didnt fix the problem.
Connecting to the auth server while logged in the vagrant box returns nothing:
```
[vagrant@localhost ~]$ wget -qO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
[vagrant@localhost ~]$
```
Tried again as root user but still no success.  

In addition to my setup: 
I'm running on a windows 7 host; I've followed the "Windows Troubleshooting" steps at https://github.com/ozone-development/ozp-documentation/wiki/Developer_Setup

**Comment by clarkjefcoat** [comment]
Try that same command with a -v instead of a -q.  That should give us more information.

```
[vagrant@localhost ~]$ wget -vO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
--2016-02-19 21:13:07--  http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json?issuerDN=None
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:8081... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8081... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json/?issuerDN=None [following]
--2016-02-19 21:13:07--  http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json/?issuerDN=None
Connecting to localhost|127.0.0.1|:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: “STDOUT”

    [<=>                                                                ] 0           --.-K/s
     {"dutyorg":"Minipax","formalAccesses":["SIERRA","TANGO","GOLF","HOTEL"],"visas":["NOVEMBER"],"dn":"Big Brothe...
    [ <=>                                                               ] 190         --.-K/s   in 0s      

2016-02-19 21:13:07 (44.9 MB/s) - written to stdout [190]
```

Also, can you run the following as a quick sanity-check to make sure something is listening on port 8081?

```
[vagrant@localhost ~]$ netstat -an | grep 8081
tcp        0      0 0.0.0.0:8081                0.0.0.0:*                   LISTEN      
[vagrant@localhost ~]$ 
```

I'll try it on my Windows8 machine and see if I run into the same problems.

**Comment by ncutt010** [comment]
Sorry for the late response.
Anyway your suggestions pointed me in the right direction.

Problem is that since I'm behind a proxy I set proxy config in my vagrant file. Resulting in the localhost request to attempt to go through the proxy.

```
[vagrant@localhost ~]$ wget -vO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
--2016-02-22 14:44:27--  http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json?issuerDN=None
Resolving contractorproxy.company.com... 157.127.239.146
Connecting to contractorproxy.company.com|157.127.239.146|:80... connected.
Proxy request sent, awaiting response... 504 Unknown Host
2016-02-22 14:44:27 ERROR 504: Unknown Host.
```

Removing the proxy settings environment variables results in:
```
[root@localhost ~]# wget -vO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
--2016-02-22 15:33:01--  http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json?issuerDN=None
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:8081... failed: Connection refused.
Connecting to localhost|127.0.0.1|:8081... connected.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json/?issuerDN=None [following]
--2016-02-22 15:33:02--  http://localhost:8081/demo-auth/users/Big%20Brother%20bigbrother/info.json/?issuerDN=None
Connecting to localhost|127.0.0.1|:8081... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: “STDOUT”

    [<=>                                                                                                                                 [ <=>

2016-02-22 15:33:02 (6.75 MB/s) - written to stdout [190]
```

After making these changes, API request in the browser now results in 502 bad_gateway errors even after restarting ngnix service.  I'm going to redo the vagrant build to see if this resolves the issue. But the original problem is because I am behind a proxy and I set proxy configs as environment variables.

Thanks!

**Comment by clarkjefcoat** [comment]
We've seen instances where vagrant doesn't always restarts services as we expect.  You might be able to solve your current issues by following the instructions at https://github.com/ozone-development/ozp-documentation/wiki/Developer_Setup#troubleshooting

Please let us know if you run into other problems.

**Comment by ncutt010** [comment]
Finally got a chance to get back to this; I realized the original issue unfortunately still exist.
I confirmed port 8081 is being listened to:
```
[root@rhel7 logs]# netstat -an | grep 8081
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN
```
I do receive fake data using wget cmd:
```
[root@rhel7logs]# wget -qO- "http://localhost:8081/demo-auth/users/Big Brother bigbrother/info.json?issuerDN=None"
{"dutyorg":"Minipax","visas":["NOVEMBER"],"clearances":["UNCLASSIFIED","CONFIDENTIAL","SECRET","TOP SECRET"],"dn":"Big Brother bigbrother","formalAccesses":["SIERRA","TANGO","GOLF","HOTEL"]}
```
Strange enough, I still get the 504 error in the ozp.log that I originally posted.  Restarting gunicorn_demoauth, gunicorn_ozp, and nginx services (in that order) had no effect. 

Note: I'm now directly running the ansible script on a RHEL 7.2 VM.  I have been somewhat successful, just running into the issue explained above.  

Thanks

**Comment by clarkjefcoat** [comment]
I hate to ask this, but are you sure it is the same error as the one you originally posted?  Does it still contain the line "Description: Unable to locate the server named "<em>localhost</em>" --- the server does not have a DNS entry."  That is really unexpected especially since the wget test works correctly for you.

As a quick sanity-check can you delete ozp.log, then do the restarts you mentioned above and post the error from ozp.log again?

**Comment by ncutt010** [comment]
No worries.  Yes I'm positive. I've cleared the log, restarted servers, and here's the error I get; same DNS error (Even changed the user in the url).
```
hitting url http://localhost:8081/demo-auth/users/Aaronson aaronson/info.json?issuerDN=None for user with dn Aaronson aaronson
Internal Server Error: /api/user/
Traceback (most recent call last):
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 377, in initial
    self.check_permissions(request)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py", line 318, in check_permissions
    if not permission.has_permission(request, self):
  File "/usr/local/ozp/backend/ozpcenter/permissions.py", line 67, in has_permission
    ozp_authorization.authorization_update(request.user.username)
  File "/usr/local/ozp/backend/ozpcenter/auth/ozp_authorization.py", line 127, in authorization_update
    updated_auth_data = _get_auth_data(username)
  File "/usr/local/ozp/backend/ozpcenter/auth/ozp_authorization.py", line 54, in _get_auth_data
    raise errors.AuthorizationFailure('Error contacting authorization server: %s' % r.text)
ozpcenter.errors.AuthorizationFailure: Error contacting authorization server: <HEAD><TITLE>Unknown Host</TITLE></HEAD>
<BODY BGCOLOR="white" FGCOLOR="black"><H1>Unknown Host</H1><HR>
<FONT FACE="Helvetica,Arial"><B>
Description: Unable to locate the server named "<em>localhost</em>" --- the server does not have a DNS entry.  Perhaps there is a misspelling in the server name, or the server no longer exists.  Double-check the name and try again.</B></FONT>
<HR>
<!-- default "Unknown Host" response (504) -->
</BODY>

```  
wget cmd still works; I even tried the "localhost:8081" URL in my web browser, and as expected I received the correct json response.

Taking a look at the "ozp_authorization.py" file, `request.get()` method passes the url along with certificate as parameters.  Even if there was issues with the cert I wouldn't expect a 504 dns error.

**Comment by clarkjefcoat** [comment]
Maybe wget is reading the no_proxy variable correctly, but python is not?  This link is old, but sounds very similar to your issue - https://github.com/kennethreitz/requests/issues/879

This link suggests setting NO_PROXY (instead of no_proxy) to get python to recognize the setting - http://stackoverflow.com/questions/28521535/requests-how-to-disable-bypass-proxy

Can you turn your proxy off and test locally?  I believe the gunicorn_ozp process only tries to connect to other ports on localhost.

**Comment by ncutt010** [comment]
This was exactly the case.  I actually was about to post that same link you referenced as I found this out right after my previous post.  Thanks for the guidance. I was under the impression this `request.get` method would pull settings out of the `no_proxy` env variable but I guess not. Weird that it pulled my `http_proxy` settings though.

Along with this update, there were a few additional modifications i made to work behind the proxy.  I can fork the repo and submit a pull request in a bit.  Might help for other who are in the same boat. I would probably just add a new variable in `all.yml` and update the ansible script to handle proxies if the variable is set.

Again, thanks for the help!

**Comment by clarkjefcoat** [comment]
Yes, please submit a pull request.  I'm sure you won't be the only person working behind a proxy.
